unit USVGPersos;

// SVG from folder "C:\Users\patrickpremartin\Documents\Embarcadero\Studio\Projets\Sporgloo\assets\graphics\Persos"
// Generated by https://github.com/DeveloppeurPascal/one-shot-tools/SVGFromFolderToStringArrayInUnit
// Last updated : 20/05/2024 13:49:12

// DON'T UPDATE THIS FILE MANUALLY, IT WILL BE ERASED ON NEXT EXPORT

interface
const
CSVGPerso1=0;
CSVGPerso10=1;
CSVGPerso11=2;
CSVGPerso12=3;
CSVGPerso13=4;
CSVGPerso14=5;
CSVGPerso15=6;
CSVGPerso16=7;
CSVGPerso17=8;
CSVGPerso18=9;
CSVGPerso19=10;
CSVGPerso2=11;
CSVGPerso20=12;
CSVGPerso21=13;
CSVGPerso22=14;
CSVGPerso23=15;
CSVGPerso24=16;
CSVGPerso3=17;
CSVGPerso4=18;
CSVGPerso5=19;
CSVGPerso6=20;
CSVGPerso7=21;
CSVGPerso8=22;
CSVGPerso9=23;
{$SCOPEDENUMS ON}
type TSVGPersosIndex = (
Perso1=CSVGPerso1,
Perso10=CSVGPerso10,
Perso11=CSVGPerso11,
Perso12=CSVGPerso12,
Perso13=CSVGPerso13,
Perso14=CSVGPerso14,
Perso15=CSVGPerso15,
Perso16=CSVGPerso16,
Perso17=CSVGPerso17,
Perso18=CSVGPerso18,
Perso19=CSVGPerso19,
Perso2=CSVGPerso2,
Perso20=CSVGPerso20,
Perso21=CSVGPerso21,
Perso22=CSVGPerso22,
Perso23=CSVGPerso23,
Perso24=CSVGPerso24,
Perso3=CSVGPerso3,
Perso4=CSVGPerso4,
Perso5=CSVGPerso5,
Perso6=CSVGPerso6,
Perso7=CSVGPerso7,
Perso8=CSVGPerso8,
Perso9=CSVGPerso9);
var SVGPersos : array of string;
implementation
initialization
setlength(SVGPersos,24);
SVGPersos[CSVGPerso1] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_90_FILL" data-name="Layer0 90 FILL">
      <path d="M4.05,22v2h8v-2H4.05M2,10v-4c-.57,0-1.03.2-1.4.6C.2,6.97,0,7.43,0,8v10C0,18.57.2,19.05.6,19.45c.37.37.83.55,1.4.55v-10M14.1,6h-.05v2h.05v12c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,18h-2.05v2h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55v-6M14.1,18h-2.05v6c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05v-2Z" fill="#157da8" stroke-width="0"/>
      <path d="M4.05,12v-2h-2.05v8h2.05v-6M14.1,10h-2.05v8h2.05v-8Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M4.05,8h-2.05v2h2.05v-2M12.05,14v-2H4.05v2h8M14.05,8h-2v2h2.05v-2h-.05M10.05,4h-4v4h4v-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,18v-4H4.05v8h8v-4M12.05,10v-2H4.05v4h8v-2Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M6.05,2l-2,2v4h2v-4h4v4h2v-4l-2-2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M2.65,2.6c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2v4h2v-4c0-.57-.18-1.03-.55-1.4l-2-2C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6l-2,2Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso10] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_96_FILL" data-name="Layer0 96 FILL">
      <path d="M6.05,10H2v8h2.05v-6h2v-2M12.05,12v6h2.05v-8h-4.05v2h2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,22v-4H4.05v4h8M10.05,8v-4h-4v4H2v2h4.05v2h-2v2h8v-2h-2v-2h4.05v-2h-4.05Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,18v-4H4.05v4h8Z" fill="#e27952" stroke-width="0"/>
      <path d="M10.05,4v-2h-4v2h4Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,6v2h4.05v10h-2.05v4H4.05v-4h-2.05v-10h4.05v-2H2c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.85-.6-1.35-.6,0,0-4.15,0-4.15,0Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M11.5.6C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v4h2V2h4v4h2V2c0-.57-.18-1.03-.55-1.4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso11] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_108_FILL" data-name="Layer0 108 FILL">
      <path d="M10.05,10v2h2v6h2.05v-8h-4.05M6.05,10H2v8h2.05v-6h2v-2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M4.05,18v4h8v-4H4.05M6.05,4v4H2v2h4.05v2h-2v2h8v-2h-2v-2h4.05v-2h-4.05v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,14v4h8v-4H4.05Z" fill="#1b914d" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M6.05,6H2c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.85-.6-1.35-.6h-4.15v2h4.05v10h-2.05v4h-8v-4h-2.05v-10h4.05v-2Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,2v4h2V2h4v4h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso12] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_102_FILL" data-name="Layer0 102 FILL">
      <path d="M6.05,10H2v8h2.05v-6h2v-2M10.05,10v2h2v6h2.05v-8h-4.05Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,18v-4H4.05v4h8Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M12.05,22v-4H4.05v4h8M10.05,6v-2h-4v4H2v2h4.05v2h-2v2h8v-2h-2v-2h4.05v-2h-4.05v-2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M10.05,4v-2h-4v2h4Z" fill="#c48647" stroke-width="0"/>
      <path d="M15.55,6.6c-.4-.4-.85-.6-1.35-.6h-4.15v2h4.05v10h-2.05v4h-8v-4h-2.05v-10h4.05v-2H2c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M11.5.6C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v4h2V2h4v4h2V2c0-.57-.18-1.03-.55-1.4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso13] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 18.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_99_FILL" data-name="Layer0 99 FILL">
      <path d="M12.05,21v-2H4.05v2h8M10.05,13v2h6v-2h-6M6.05,13h-2v2h2v-2M6.05,5v4l2,2,2-2v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,23v-2H4.05v2h8M16.05,15h-2v8h2v-8M6.05,9H2v2h2.05v2h2v2h4v-2h6v-4h-6l-2,2-2-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M18.05,9h-2v14h-2v-8h-2v8h-8v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-14Z" fill="#9a6836" stroke-width="0"/>
      <path d="M6.05,15h-2v4h8v-4h-6M4.05,5v4h2v-4h4v4h2v-4l-2-2h-4l-2,2M15.05,2l-1,1v6h2V3s-1-1-1-1Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M4.05,13v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M.05,8.55c-.03.1-.05.23-.05.4v10.15c0,.13.02.27.05.4.07.33.25.65.55.95.37.37.83.55,1.4.55h2.05v-2h-2.05V7c-.57,0-1.03.2-1.4.6-.3.27-.48.58-.55.95Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M11.5,1.6c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2v4h2V3l1-1,1,1v6h2V3c0-.57-.18-1.03-.55-1.4l-1-1C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7,0,0-.7-.7-.7-.7Z" fill="#686d6d" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso14] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 18.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_105_FILL" data-name="Layer0 105 FILL">
      <path d="M12.05,21v-2H4.05v2h8M16.05,13h-6v2h6v-2M6.05,13h-2v2h2v-2M6.05,9l2,2,2-2v-4h-4v4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,23v-2H4.05v2h8M16.05,15h-2v8h2v-8M2,9v2h2.05v2h2v2h4v-2h6v-4h-6l-2,2-2-2H2Z" fill="#c48647" stroke-width="0"/>
      <path d="M12.05,19v-4H4.05v4h8M6.05,3l-2,2v4h2v-4h4v4h2v-4l-2-2h-4Z" fill="#1b914d" stroke-width="0"/>
      <path d="M18.05,9h-2v14h-2v-8h-2v8h-8v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-14Z" fill="#9a6836" stroke-width="0"/>
      <path d="M16.05,3l-1-1-1,1v6h2V3Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M4.05,13v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2,11v-4c-.57,0-1.03.2-1.4.6-.3.27-.48.58-.55.95C.02,8.65,0,8.78,0,8.95v10.15C0,19.23.02,19.37.05,19.5c.07.33.25.65.55.95.37.37.83.55,1.4.55h2.05v-2h-2.05s0-8,0-8Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,5l2-2h4l2,2,.15-2.7-.7-.7c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4Z" fill="#115f32" stroke-width="0"/>
      <path d="M15.05,0C14.48,0,14.02.2,13.65.6l-1,1c-.23.2-.38.43-.45.7l-.15,2.7v4h2V3l1-1,1,1v6h2V3c0-.57-.18-1.03-.55-1.4l-1-1C16.1.2,15.62,0,15.05,0Z" fill="#686d6d" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso15] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 18.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_93_FILL" data-name="Layer0 93 FILL">
      <path d="M12.05,23v-2H4.05v2h8M16.05,15h-2v8h2v-8M6.05,9H2v2h2.05v2h2v2h4v-2h6v-4h-6l-2,2-2-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M6.05,13h-2v2h2v-2M12.05,21v-2H4.05v2h8M16.05,13h-6v2h6v-2M6.05,5v4l2,2,2-2v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,13v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,19v-4H4.05v4h8M4.05,9h2v-4h4v4h2v-4l-2-2h-4l-2,2v4Z" fill="#e27952" stroke-width="0"/>
      <path d="M18.05,9h-2v14h-2v-8h-2v8h-8v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-14Z" fill="#9a6836" stroke-width="0"/>
      <path d="M16.05,3l-1-1-1,1v6h2V3Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M18.05,3c0-.57-.18-1.03-.55-1.4l-1-1C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7l-.15,2.7v4h2V3l1-1,1,1v6h2s0-6,0-6Z" fill="#686d6d" stroke-width="0"/>
      <path d="M.05,8.55c-.03.1-.05.23-.05.4v10.15c0,.13.02.27.05.4.07.33.25.65.55.95.37.37.83.55,1.4.55h2.05v-2h-2.05V7c-.57,0-1.03.2-1.4.6-.3.27-.48.58-.55.95Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M6.05,1c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2,.15-2.7-.7-.7c-.4-.4-.88-.6-1.45-.6,0,0-4,0-4,0Z" fill="#a6583c" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso16] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 18.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_88_FILL" data-name="Layer0 88 FILL">
      <path d="M12.05,19H4.05v2h8v-2M6.05,13h-2v2h2v-2M10.05,15h6v-2h-6v2M10.05,5h-4v4l2,2,2-2v-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,21v2h8v-2H4.05M16.05,15h-2v8h2v-8M16.05,13v-4h-6l-2,2-2-2H2v2h2.05v2h2v2h4v-2h6Z" fill="#c48647" stroke-width="0"/>
      <path d="M.05,8.55c-.03.1-.05.23-.05.4v10.15c0,.13.02.27.05.4.07.33.25.65.55.95.37.37.83.55,1.4.55h2.05v-2h-2.05V7c-.57,0-1.03.2-1.4.6-.3.27-.48.58-.55.95Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,13v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,15H4.05v4h8v-4M6.05,3l-2,2v4h2v-4h4v4h2v-4l-2-2h-4Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M16.05,9v14h-2v-8h-2v8h-8v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-14h-2Z" fill="#9a6836" stroke-width="0"/>
      <path d="M15.05,2l-1,1v6h2V3s-1-1-1-1Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M16.5.6C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7l-.15,2.7v4h2V3l1-1,1,1v6h2V3c0-.57-.18-1.03-.55-1.4,0,0-1-1-1-1Z" fill="#686d6d" stroke-width="0"/>
      <path d="M2.65,3.6c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2,.15-2.7-.7-.7c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2Z" fill="#157da8" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso17] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_92_FILL" data-name="Layer0 92 FILL">
      <path d="M14.05,15v8h2v-8h-2M4.05,21v2h8v-2h-8M4.05,15v4h4v-4h-4M2.05,9h-.05v2h2.05v2h12v-4h-6l-2,2-2-2s-4,0-4,0Z" fill="#c48647" stroke-width="0"/>
      <path d="M12.05,19h-1.95v2h1.95v-2M16.05,15v-2h-5.95v2h5.95M10.05,5h-4v4l2,2,2-2v-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M10.1,15v4h1.95v-4h-1.95M12.05,5l-2-2h-4l-2,2v4h2v-4h4v4h2v-4Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M4.05,23h-2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-12h-2v12h-2v-8h-2v8h-8M2.05,7h-.05c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v4h2v-4h.05v-2Z" fill="#9a6836" stroke-width="0"/>
      <path d="M2,13H0v8c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-8M12.2,2.3l-.15,2.7v4h2V3l1-1,1,1v4h2v2h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6v-2c0-.57-.18-1.03-.55-1.4l-1-1C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7Z" fill="#686d6d" stroke-width="0"/>
      <path d="M4.05,13h-2.05v8h8.1v-8h-6.05M4.05,19v-4h4v4h-4M16.05,7V3l-1-1-1,1v6h4v-2h-2Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M2,13h2.05v-2h-2.05s0,2,0,2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,5l.15-2.7-.7-.7c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v4h2v-4l2-2h4l2,2Z" fill="#157da8" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso18] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_97_FILL" data-name="Layer0 97 FILL">
      <path d="M14.05,15v8h2v-8h-2M4.05,21v2h8v-2h-8M4.05,15v4h4v-4h-4M14.05,9h-4l-2,2-2-2H2v2h2.05v2h12v-4s-2,0-2,0Z" fill="#c48647" stroke-width="0"/>
      <path d="M12.05,19h-1.95v2h1.95v-2M16.05,15v-2h-5.95v2h5.95M6.05,5v4l2,2,2-2v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,15h-1.95v4h1.95v-4M6.05,9v-4h4v4h2v-4l-2-2h-4l-2,2v4h2Z" fill="#e27952" stroke-width="0"/>
      <path d="M4.05,23h-2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-12h-2v12h-2v-8h-2v8h-8M2.05,7h-.05c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v4h2v-4h.05v-2Z" fill="#9a6836" stroke-width="0"/>
      <path d="M4.05,13h-2.05v8h8.1v-8h-6.05M4.05,19v-4h4v4h-4M14.05,3v6h4v-2h-2V3l-1-1s-1,1-1,1Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M2,13H0v8c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-8M12.65,1.6c-.23.2-.38.43-.45.7l-.15,2.7v4h2V3l1-1,1,1v4h2v2h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6v-2c0-.57-.18-1.03-.55-1.4l-1-1C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6c0,0-1,1-1,1Z" fill="#686d6d" stroke-width="0"/>
      <path d="M2,11v2h2.05v-2h-2.05Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M11.5,1.6c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v4h2v-4l2-2h4l2,2,.15-2.7s-.7-.7-.7-.7Z" fill="#a6583c" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso19] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_109_FILL" data-name="Layer0 109 FILL">
      <path d="M12.05,19h-1.95v2h1.95v-2M16.05,13h-5.95v2h5.95v-2M6.05,9l2,2,2-2v-4h-4v4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,15h-1.95v4h1.95v-4M12.05,5l-2-2h-4l-2,2v4h2v-4h4v4h2v-4Z" fill="#1b914d" stroke-width="0"/>
      <path d="M16.05,23v-8h-2v8h2M4.05,21v2h8v-2h-8M4.05,15v4h4v-4h-4M8.05,11l-2-2H2v2h2.05v2h12v-4h-6s-2,2-2,2Z" fill="#c48647" stroke-width="0"/>
      <path d="M2,13H0v8c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-8M16.5.6C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7l-.15,2.7v4h2V3l1-1,1,1v4h2v2h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6v-2c0-.57-.18-1.03-.55-1.4,0,0-1-1-1-1Z" fill="#686d6d" stroke-width="0"/>
      <path d="M4.05,13h-2.05v8h8.1v-8h-6.05M4.05,19v-4h4v4h-4M14.05,3v6h4v-2h-2V3l-1-1s-1,1-1,1Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M4.05,11h-2.05v2h2.05v-2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2.05,7h-.05c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v4h2v-4h.05v-2M18.05,11h-2v12h-2v-8h-2v8H2.05c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-12Z" fill="#9a6836" stroke-width="0"/>
      <path d="M10.05,1h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v4h2v-4l2-2h4l2,2,.15-2.7-.7-.7c-.4-.4-.88-.6-1.45-.6Z" fill="#115f32" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso2] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_95_FILL" data-name="Layer0 95 FILL">
      <path d="M4.05,22v2h8v-2H4.05M14.05,6v2h.05v12c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6h-.05M.6,6.6c-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55V6c-.57,0-1.03.2-1.4.6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,18h-2.05v2h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55v-6M14.1,20v-2h-2.05v6c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05Z" fill="#a6583c" stroke-width="0"/>
      <path d="M4.05,12v-2h-2.05v8h2.05v-6M14.1,10h-2.05v8h2.05v-8Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,18v-4H4.05v8h8v-4M6.05,8h-2v4h8v-4h-6Z" fill="#e27952" stroke-width="0"/>
      <path d="M12.05,14v-2H4.05v2h8M14.1,8h-2.05v2h2.05v-2M6.05,4v4h4v-4h-4M4.05,8h-2.05v2h2.05v-2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,8h2v-4h4v4h2v-4l-2-2h-4l-2,2v4Z" fill="#c48647" stroke-width="0"/>
      <path d="M11.5.6C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2v4h2v-4c0-.57-.18-1.03-.55-1.4,0,0-2-2-2-2Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso20] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.05 25">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_103_FILL" data-name="Layer0 103 FILL">
      <path d="M10.1,19v2h1.95v-2h-1.95M10.1,13v2h5.95v-2h-5.95M10.05,9v-4h-4v4l2,2,2-2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,21v2h8v-2H4.05M16.05,15h-2v8h2v-8M4.05,15v4h4v-4h-4M12.05,9h-2l-2,2-2-2H2v2h2.05v2h12v-4h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M2,13H0v8c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-8M16.5.6C16.1.2,15.62,0,15.05,0s-1.03.2-1.4.6l-1,1c-.23.2-.38.43-.45.7l-.7-.7c-.4-.4-.88-.6-1.45-.6h-4c-.57,0-1.03.2-1.4.6l-2,2c-.4.37-.6.83-.6,1.4v4h2v-4l2-2h4l2,2v4h2V3l1-1,1,1v4h2v2h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6v-2c0-.57-.18-1.03-.55-1.4,0,0-1-1-1-1Z" fill="#686d6d" stroke-width="0"/>
      <path d="M2,11v2h2.05v-2h-2.05Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2.05,9v-2h-.05c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v4h2v-4h.05M14.05,15h-2v8H2.05c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.37,0,.7-.08,1-.25.3.17.63.25,1,.25h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-12h-2v12h-2s0-8,0-8Z" fill="#9a6836" stroke-width="0"/>
      <path d="M10.1,15v-2H2v8h8.1v-2h1.95v-4h-1.95M4.05,19v-4h4v4h-4M10.05,3h-4l-2,2v4h2v-4h4v4h2v-4l-2-2M16.05,3l-1-1-1,1v6h4v-2h-2V3Z" fill="#acb8b8" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso21] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_100_FILL" data-name="Layer0 100 FILL">
      <path d="M2,18H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-4M16.05,18.5c.03-.17.05-.33.05-.5h-2.05v4h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-3.5M15.55,6.6c-.4-.4-.88-.6-1.45-.6h-2.05v-2h-2v4h4.05v4h2v-4c0-.57-.18-1.03-.55-1.4M6.05,6v-2h-2v2H2c-.57,0-1.03.2-1.4.6C.2,6.97,0,7.43,0,8v4H2v-4h4.05v-2Z" fill="#686d6d" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8Z" fill="#9a6836" stroke-width="0"/>
      <path d="M12.05,20H4.05v2h8v-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M14.1,12l-2.05,2v4h2.05v-6M4.05,14l-2.05-2v6h2.05v-4Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M16.1,12h-2v6h2v-6M2,12H0v6h2v-6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,12h-2v8h2v2h2v-4h-2v-4l2.05-2v-4h-2.05v4M6.3,12h-2.25v-4h-2.05v4l2.05,2v4h-2.05v4h2.05v-2h2.25v-8Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#fc0" stroke-width="0"/>
      <path d="M6.05,8h-2v4h2.25v8h3.75v-8h2v-4h-2v2h-4v-2Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M6.05,6v4h4v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M6.05,4v2h4v-2h-4Z" fill="#7b7360" stroke-width="0"/>
      <path d="M6.05,0C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v2h2v-2h4v2h2v-2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4Z" fill="#c69d00" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso22] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_106_FILL" data-name="Layer0 106 FILL">
      <path d="M2,18H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-4M16.05,18.5c.03-.17.05-.33.05-.5h-2.05v4h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-3.5M12.05,4h-2v4h4.05v4h2v-4c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6h-2.05v-2M6.05,6v-2h-2v2H2c-.57,0-1.03.2-1.4.6C.2,6.97,0,7.43,0,8v4H2v-4h4.05v-2Z" fill="#115f32" stroke-width="0"/>
      <path d="M4.05,18v-4l-2.05-2v6h2.05M14.05,18h.05v-6l-2.05,2v4h2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,22v-2H4.05v2h8Z" fill="#c48647" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8Z" fill="#9a6836" stroke-width="0"/>
      <path d="M16.1,12h-2v6h2v-6M2,12H0v6h2v-6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,8v4h-2v8h2v2h2v-4h-2v-4l2.05-2v-4h-2.05M2,8v4l2.05,2v4h-2.05v4h2.05v-2h2.25v-8h-2.25v-4h-2.05Z" fill="#1b914d" stroke-width="0"/>
      <path d="M6.05,8v2h4v-4h-4v2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M6.05,8h-2v4h2.25v8h3.75v-8h2v-4h-2v2h-4v-2Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M6.05,4v2h4v-2h-4Z" fill="#7b7360" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#fc0" stroke-width="0"/>
      <path d="M6.05,4v-2h4v2h2v-2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v2h2Z" fill="#c69d00" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso23] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_94_FILL" data-name="Layer0 94 FILL">
      <path d="M2,12v6h2.05v-4l-2.05-2M14.05,18h.05v-6l-2.05,2v4h2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2,18H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-4M16.05,18.5c.03-.17.05-.33.05-.5h-2.05v4h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-3.5M12.05,4h-2v4h4.05v4h2v-4c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6h-2.05v-2M.6,6.6c-.4.37-.6.83-.6,1.4v4h2v-4h4.05v-4h-2v2h-2.05c-.57,0-1.03.2-1.4.6Z" fill="#a6583c" stroke-width="0"/>
      <path d="M2,12H0v6h2v-6M16.1,12h-2v6h2v-6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8Z" fill="#9a6836" stroke-width="0"/>
      <path d="M12.05,20H4.05v2h8v-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M14.1,8h-2.05v4h-2v8h2v2h2v-4h-2v-4l2.05-2v-4M4.05,8h-2.05v4l2.05,2v4h-2.05v4h2.05v-2h2.25v-8h-2.25v-4Z" fill="#e27952" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#fc0" stroke-width="0"/>
      <path d="M6.05,4v2h4v-2h-4Z" fill="#7b7360" stroke-width="0"/>
      <path d="M6.05,6v4h4v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M6.05,8h-2v4h2.25v8h3.75v-8h2v-4h-2v2h-4v-2Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M6.05,0C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v2h2v-2h4v2h2v-2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4Z" fill="#c69d00" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso24] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_89_FILL" data-name="Layer0 89 FILL">
      <path d="M4.05,18v-4l-2.05-2v6h2.05M12.05,14v4h2.05v-6l-2.05,2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2,18H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05v-4M14.1,18h-.05v4h-2v2h2c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-3.5c.03-.17.05-.33.05-.5h-2M12.05,4h-2v4h4.05v4h2v-4c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6h-2.05v-2M4.05,4v2H2c-.57,0-1.03.2-1.4.6C.2,6.97,0,7.43,0,8v4H2v-4h4.05v-4h-2Z" fill="#157da8" stroke-width="0"/>
      <path d="M2,12H0v6h2v-6M16.1,12h-2v6h2v-6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,12v-4h-2.05v4l2.05,2v4h-2.05v4h2.05v-2h2.25v-8h-2.25M14.1,12v-4h-2.05v4h-2v8h2v2h2v-4h-2v-4l2.05-2Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8Z" fill="#9a6836" stroke-width="0"/>
      <path d="M12.05,20H4.05v2h8v-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,12h2v-4h-2v2h-4v-2h-2v4h2.25v8h3.75v-8Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M10.05,6h-4v4h4v-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M6.05,4v2h4v-2h-4Z" fill="#7b7360" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#fc0" stroke-width="0"/>
      <path d="M4.65.6c-.4.37-.6.83-.6,1.4v2h2v-2h4v2h2v-2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6Z" fill="#c69d00" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso3] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_107_FILL" data-name="Layer0 107 FILL">
      <path d="M4.05,18h-2.05v2h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55v-6M14.1,18h-2.05v6c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05v-2Z" fill="#115f32" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8M14.1,6h-.05v2h.05v12c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6M.6,6.6c-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55V6c-.57,0-1.03.2-1.4.6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,18v-4H4.05v8h8v-4M6.05,8h-2v4h8v-4h-6Z" fill="#1b914d" stroke-width="0"/>
      <path d="M12.05,12H4.05v2h8v-2M14.1,8h-2.05v2h2.05v-2M10.05,8v-4h-4v4h4M4.05,8h-2.05v2h2.05v-2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M14.1,10h-2.05v8h2.05v-8M4.05,12v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M6.05,2l-2,2v4h2v-4h4v4h2v-4l-2-2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,0h-4C5.48,0,5.02.2,4.65.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2v4h2v-4c0-.57-.18-1.03-.55-1.4l-2-2C11.1.2,10.62,0,10.05,0Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso4] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_101_FILL" data-name="Layer0 101 FILL">
      <path d="M4.05,18h-2.05v2h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55v-6M14.1,18h-2.05v6c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05v-2Z" fill="#686d6d" stroke-width="0"/>
      <path d="M12.05,24v-2H4.05v2h8M14.1,6h-.05v2h.05v12c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.88-.6-1.45-.6M.6,6.6c-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55V6c-.57,0-1.03.2-1.4.6Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,14H4.05v8h8v-8M6.05,8h-2v4h8v-4h-6Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M12.05,12v6h2.05v-8h-2.05v2M4.05,12v-2h-2.05v8h2.05v-6Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M14.1,8h-2.05v2h2.05v-2M4.05,12v2h8v-2H4.05M4.05,8h-2.05v2h2.05v-2M10.05,8v-4h-4v4h4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M10.05,2h-4l-2,2v4h2v-4h4v4h2v-4l-2-2Z" fill="#c48647" stroke-width="0"/>
      <path d="M4.65.6l-2,2c-.4.37-.6.83-.6,1.4v2h-.05v2h2.05v-4l2-2h4l2,2v4h2v-4c0-.57-.18-1.03-.55-1.4l-2-2C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso5] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.1 26">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_87_FILL" data-name="Layer0 87 FILL">
      <path d="M2.05,22v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8v-2H4.05v-2h-2M4.05,2v6h-2.05c-.57,0-1.03.2-1.4.6C.2,8.97,0,9.43,0,10v6h2v-6h4.05V2h4v8h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4Z" fill="#157da8" stroke-width="0"/>
      <path d="M4.05,18v-2h-2.05v4h2.05v-2M16.1,18v-4h-2v1.75l.05,2.25h1.95Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2,16H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05s0-4,0-4Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,10h-2.05v6h2.05v-6M12.05,18h-2v-6h-4v6h-2v6h8v-6M14.1,14h-2.05v4h2.05v-4M12.1,10h-.05v2.25l.05-2.25M6.05,8h4V2h-4v6Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M6.05,12v-2h-2v8h2v-6M12.05,14v-4h-2v8h2v-4Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M16.1,24v-6h-1.95v2h-.05v4h2M14.1,2v2h2v2h-2v4h.05l-.05,4h2v-6l2-2V2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,8h-4v4h4v-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M14.1,0C13.53,0,13.07.2,12.7.6c-.4.37-.6.83-.6,1.4h-.05v8h.05l-.05,2.25v1.75h2.05l.05-4h-.05v-4h2v-2h-2v-2h4v4l-2,2v16h-2v-4h.05v-2h-2.1v8h4.1c.53,0,1-.18,1.4-.55.37-.4.55-.88.55-1.45v-15.15l1.45-1.4c.37-.4.55-.88.55-1.45V2c0-.57-.18-1.03-.55-1.4C19.15.2,18.67,0,18.1,0h-4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso6] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.1 26">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_98_FILL" data-name="Layer0 98 FILL">
      <path d="M4.05,22h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8v-2H4.05v-2M2,10h4.05V2h4v8h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v6h-2.05c-.57,0-1.03.2-1.4.6C.2,8.97,0,9.43,0,10v6h2v-6Z" fill="#a6583c" stroke-width="0"/>
      <path d="M2,16H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05s0-4,0-4Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M4.05,16h-2.05v4h2.05v-4M16.1,18v-4h-2v1.75l.05,2.25h1.95Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.05,18h-2v-6h-4v6h-2v6h8v-6M14.1,15.75v-1.75h-2.05v4h2.05v-2.25M6.05,8h4V2h-4v6M4.05,10h-2.05v6h2.05v-6Z" fill="#e27952" stroke-width="0"/>
      <path d="M16.1,24v-6h-1.95v2h-.05v4h2M14.1,2v2h2v2h-2v4h.05l-.05,4h2v-6l2-2V2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M6.05,10h-2v8h2v-8M12.05,10h-2v8h2v-8Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M12.1,10h-.05v2.25l.05-2.25Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M6.05,8v4h4v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M14.1,4v-2h4v4l-2,2v16h-2v-4h.05v-2h-2.1v8h4.1c.53,0,1-.18,1.4-.55.37-.4.55-.88.55-1.45v-15.15l1.45-1.4c.37-.4.55-.88.55-1.45V2c0-.57-.18-1.03-.55-1.4C19.15.2,18.67,0,18.1,0h-4C13.53,0,13.07.2,12.7.6c-.4.37-.6.83-.6,1.4h-.05v8h.05l-.05,2.25v1.75h2.05l.05-4h-.05v-4h2v-2h-2Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso7] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.1 26">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_110_FILL" data-name="Layer0 110 FILL">
      <path d="M2,16v4h2.05v-4h-2.05M16.1,14h-2v1.75l.05,2.25h1.95v-4Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M2,20v-4H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M12.05,26v-2H4.05v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8M6.05,0C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v6h-2.05c-.57,0-1.03.2-1.4.6C.2,8.97,0,9.43,0,10v6h2v-6h4.05V2h4v8h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4Z" fill="#115f32" stroke-width="0"/>
      <path d="M16.1,24v-6h-1.95v2h-.05v4h2M14.1,10h.05l-.05,4h2v-6l2-2V2h-4v2h2v2h-2v4Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,12h-4v6h-2v6h8v-6h-2v-6M14.1,14h-2.05v4h2.05v-4M4.05,10h-2.05v6h2.05v-6M10.05,2h-4v6h4V2Z" fill="#1b914d" stroke-width="0"/>
      <path d="M12.05,14v-4h-2v8h2v-4M6.05,12v-2h-2v8h2v-6Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M12.1,10h-.05v2.25l.05-2.25Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M6.05,10v2h4v-4h-4v2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.1,2h-.05v8h.05l-.05,2.25v1.75h2.05l.05-4h-.05v-4h2v-2h-2v-2h4v4l-2,2v16h-2v-4h.05v-2h-2.1v8h4.1c.53,0,1-.18,1.4-.55.37-.4.55-.88.55-1.45v-15.15l1.45-1.4c.37-.4.55-.88.55-1.45V2c0-.57-.18-1.03-.55-1.4C19.15.2,18.67,0,18.1,0h-4C13.53,0,13.07.2,12.7.6c-.4.37-.6.83-.6,1.4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso8] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 20.1 26">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_104_FILL" data-name="Layer0 104 FILL">
      <path d="M12.05,26v-2H4.05v-2h-2v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8M6.05,0C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4v6h-2.05c-.57,0-1.03.2-1.4.6C.2,8.97,0,9.43,0,10v6h2v-6h4.05V2h4v8h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4Z" fill="#686d6d" stroke-width="0"/>
      <path d="M16.1,24v-6h-1.95v2h-.05v4h2M14.1,2v2h2v2h-2v4h.05l-.05,4h2v-6l2-2V2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M10.05,12h-4v6h-2v6h8v-6h-2v-6M14.1,15.75v-1.75h-2.05v4h2.05v-2.25M4.05,10h-2.05v6h2.05v-6M10.05,2h-4v6h4V2Z" fill="#acb8b8" stroke-width="0"/>
      <path d="M14.1,14v1.75l.05,2.25h1.95v-4h-2M4.05,16h-2.05v4h2.05v-4Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M12.1,10h-.05v2.25l.05-2.25Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M10.05,10v-2h-4v4h4v-2Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M12.05,10h-2v8h2v-8M4.05,10v8h2v-8h-2Z" fill="#f5f5f5" stroke-width="0"/>
      <path d="M2,16H0v4c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h2.05v-2h-2.05s0-4,0-4Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M14.1,4v-2h4v4l-2,2v16h-2v-4h.05v-2h-2.1v8h4.1c.53,0,1-.18,1.4-.55.37-.4.55-.88.55-1.45v-15.15l1.45-1.4c.37-.4.55-.88.55-1.45V2c0-.57-.18-1.03-.55-1.4C19.15.2,18.67,0,18.1,0h-4C13.53,0,13.07.2,12.7.6c-.4.37-.6.83-.6,1.4h-.05v8h.05l-.05,2.25v1.75h2.05l.05-4h-.05v-4h2v-2h-2Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
SVGPersos[CSVGPerso9] := '''
<?xml version="1.0" encoding="UTF-8"?>
<svg id="Calque_2" data-name="Calque 2" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16.1 24">
  <g id="Calque_1-2" data-name="Calque 1-2">
    <g id="Layer0_91_FILL" data-name="Layer0 91 FILL">
      <path d="M10.05,12h2v6h2.05v-8h-4.05v2M6.05,12v-2H2v8h2.05v-6h2Z" fill="#e9c07f" stroke-width="0"/>
      <path d="M4.05,18v4h8v-4H4.05M6.05,4v4H2v2h4.05v2h-2v2h8v-2h-2v-2h4.05v-2h-4.05v-4h-4Z" fill="#ffd18b" stroke-width="0"/>
      <path d="M4.05,14v4h8v-4H4.05Z" fill="#1ea7e1" stroke-width="0"/>
      <path d="M6.05,6H2c-.57,0-1.03.2-1.4.6-.4.37-.6.83-.6,1.4v10c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h.05v2c0,.57.2,1.05.6,1.45.37.37.83.55,1.4.55h8c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-2h.05c.57,0,1.05-.18,1.45-.55.37-.4.55-.88.55-1.45v-10c0-.57-.18-1.03-.55-1.4-.4-.4-.85-.6-1.35-.6h-4.15v2h4.05v10h-2.05v4h-8v-4h-2.05v-10h4.05v-2Z" fill="#af8f5e" stroke-width="0"/>
      <path d="M6.05,2v2h4v-2h-4Z" fill="#c48647" stroke-width="0"/>
      <path d="M4.05,2v4h2V2h4v4h2V2c0-.57-.18-1.03-.55-1.4C11.1.2,10.62,0,10.05,0h-4C5.48,0,5.02.2,4.65.6c-.4.37-.6.83-.6,1.4Z" fill="#9a6836" stroke-width="0"/>
    </g>
  </g>
</svg>
''';
end.
